---
name: "Extends Jellyfin daily shows date format"
guid: "be32c1b1-426a-467a-ae34-9182e1736f54"
version: "1.2.0.0"
targetAbi: "10.7.0.0"
owner: "arabcoders"
overview: "Parse more date format for daily shows."
description: "This plugin add support for more date format for daily shows."
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.DAILYExtender.dll"
changelog: >
  changelog
